# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2018-02-13 07:40:03 +0000 by root:
gem "rspec", "~> 3.7", :group => [:test]
